//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGeneratorUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeGeneratorUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add database.
        /// </summary>
        public static string add_database {
            get {
                return ResourceManager.GetString("add_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add template.
        /// </summary>
        public static string add_template {
            get {
                return ResourceManager.GetString("add_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click on the button below to add one.
        /// </summary>
        public static string click_on_the_button_below_to_add_one {
            get {
                return ResourceManager.GetString("click_on_the_button_below_to_add_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code Editor.
        /// </summary>
        public static string code_editor {
            get {
                return ResourceManager.GetString("code_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code Generator.
        /// </summary>
        public static string code_generator {
            get {
                return ResourceManager.GetString("code_generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ConnectionString.
        /// </summary>
        public static string connectionstring {
            get {
                return ResourceManager.GetString("connectionstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy.
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy that stuff.
        /// </summary>
        public static string copy_that_stuff {
            get {
                return ResourceManager.GetString("copy_that_stuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cut.
        /// </summary>
        public static string cut {
            get {
                return ResourceManager.GetString("cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Database.
        /// </summary>
        public static string database {
            get {
                return ResourceManager.GetString("database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Database Connected and Saved Successfull.
        /// </summary>
        public static string database_connected_and_saved_successfull {
            get {
                return ResourceManager.GetString("database_connected_and_saved_successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Databases.
        /// </summary>
        public static string databases {
            get {
                return ResourceManager.GetString("databases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field is required.
        /// </summary>
        public static string field_is_required {
            get {
                return ResourceManager.GetString("field_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File deleted successfull.
        /// </summary>
        public static string file_deleted_successfull {
            get {
                return ResourceManager.GetString("file_deleted_successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File saved successfull.
        /// </summary>
        public static string file_saved_successfull {
            get {
                return ResourceManager.GetString("file_saved_successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generate!.
        /// </summary>
        public static string generate {
            get {
                return ResourceManager.GetString("generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go to Github.
        /// </summary>
        public static string go_to_github {
            get {
                return ResourceManager.GetString("go_to_github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify.
        /// </summary>
        public static string modify {
            get {
                return ResourceManager.GetString("modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Move to recycle bin.
        /// </summary>
        public static string move_to_recycle_bin {
            get {
                return ResourceManager.GetString("move_to_recycle_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No databases to show.
        /// </summary>
        public static string no_databases_to_show {
            get {
                return ResourceManager.GetString("no_databases_to_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No templates to show.
        /// </summary>
        public static string no_templates_to_show {
            get {
                return ResourceManager.GetString("no_templates_to_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open.
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Owner (For MySql databases).
        /// </summary>
        public static string owner_for_mysql_databases {
            get {
                return ResourceManager.GetString("owner_for_mysql_databases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste.
        /// </summary>
        public static string paste {
            get {
                return ResourceManager.GetString("paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste some stuff.
        /// </summary>
        public static string paste_some_stuff {
            get {
                return ResourceManager.GetString("paste_some_stuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provider.
        /// </summary>
        public static string provider {
            get {
                return ResourceManager.GetString("provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Schema.
        /// </summary>
        public static string schema {
            get {
                return ResourceManager.GetString("schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a provider.
        /// </summary>
        public static string select_a_provider {
            get {
                return ResourceManager.GetString("select_a_provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show in explorer.
        /// </summary>
        public static string show_in_explorer {
            get {
                return ResourceManager.GetString("show_in_explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tables.
        /// </summary>
        public static string tables {
            get {
                return ResourceManager.GetString("tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Templates.
        /// </summary>
        public static string templates {
            get {
                return ResourceManager.GetString("templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must add at least one database and one set of templates in order to continue..
        /// </summary>
        public static string you_must_add_at_least_one_database_and_one_set_of_templates_in_order_to_continue {
            get {
                return ResourceManager.GetString("you_must_add_at_least_one_database_and_one_set_of_templates_in_order_to_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select a database.
        /// </summary>
        public static string you_must_select_a_database {
            get {
                return ResourceManager.GetString("you_must_select_a_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select an option.
        /// </summary>
        public static string you_must_select_an_option {
            get {
                return ResourceManager.GetString("you_must_select_an_option", resourceCulture);
            }
        }
    }
}
